FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Bucket List Service API

BLiSA is a simple API allowing users to _CREATE bucketlists_ and _items_ in them. Then they are able to _VIEW_, _UPDATE_ and _DELETE_ them.

## User Authentification [/auth/login/]

### Logs a user in [POST]

+ Request (application/json)

        {
            "username": "us3rn@m3",
            "password": "p@ssw0rd"
        }

+ Response 200 (application/json)

        {
            "token": "t0k3n"
        }

## User Registration [/auth/register/]

### Register a user [POST]

+ Request (application/json)

        {
            "username": "us3rn@m3",
            "email": "email@user.com",
            "password": "p@ssw0rd",
            "confirm_password": "p@ssw0rd"
        }

+ Response 201 (application/json)

        {
            "message": "Successful registration"
        }

## Bucket List Collection [/bucketlists/]

### Create a New Bucket List [POST]

+ Request (application/json)

    + Headers

                Authorization: JWT Token

    + Body

            {
                "name": "BucketList1",
                "items": [],
                "date_created": "2015-08-12 11:57:23",
                "date_modified": "2015-08-12 11:57:23",
                "created_by": "1113456"
            }

+ Response 201 (application/json)

        {
            "id": 1,
            "name": "BucketList1",
            "items": [],
            "date_created": "2015-08-12 11:57:23",
            "date_modified": "2015-08-12 11:57:23",
            "created_by": "1113456"
        }


### List All Bucket Lists [GET]

+ Request (application/json)

    + Headers

                Authorization: JWT Token

+ Response 200 (application/json)

        {
            [
                {
                    "id": 1,
                    "name": "BucketList1"
                },
                {
                    "id": 2,
                    "name": "BucketList2"
                },
                {
                    "id": 3,
                    "name": "BucketList3"
                }
            ]
        }

## Single Bucketlist [/bucketlists/<id>]

### Get Single Bucket List [GET]

+ Request (application/json)

    + Headers

                Authorization: JWT Token

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "BucketList1",
            "items": [
                {
                    "item_id": 1,
                    "name": "I need to do X",
                    "date_created": "2015-08-12 11:57:23",
                    "date_modified": "2015-08-12 11:57:23",
                    "done": False
                },
                {
                    "item_id": 2,
                    "name": "I need to do Y",
                    "date_created": "2015-08-12 11:59:23",
                    "date_modified": "2015-08-12 11:59:23",
                    "done": True
                }
            ],
            "date_created": "2015-08-12 11:57:23",
            "date_modified": "2015-08-12 11:57:23",
            "created_by": "1113456"
        }

### Update this Bucket List [PUT]

+ Request (application/json)

    + Headers

            Authorization: JWT Token

    + Body

            {
                "name": "BucketList5",
                "date_modified": "2015-08-12 11:59:23",
            }

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "BucketList5",
            "items": [
                {
                    "item_id": 1,
                    "name": "I need to do X",
                    "date_created": "2015-08-12 11:57:23",
                    "date_modified": "2015-08-12 11:57:23",
                    "done": False
                },
                {
                    "item_id": 2,
                    "name": "I need to do Y",
                    "date_created": "2015-08-12 11:59:23",
                    "date_modified": "2015-08-12 11:59:23",
                    "done": True
                }
            ],
            "date_created": "2015-08-12 11:57:23",
            "date_modified": "2015-08-12 11:59:23",
            "created_by": "1113456"
        }

### Delete this single Bucket List [DELETE]

+ Request (application/json)

    + Headers

            Authorization: JWT Token

+ Response 204 (application/json)

## Items in a Bucketlist [/bucketlists/<id>/items/]

### Create new Item in Bucket List [POST]

+ Request (application/json)

    + Headers

            Authorization: JWT Token

    + Body

            {
                "id": 1,
                "bl_id": 1,
                "name": "I need to do X",
                "date_created": "2015-08-12 11:57:23",
                "done": False
            }

+ Response 201 (application/json)

        {
            "id": 1,
            "item_id": 1,
            "name": "I need to do X",
            "date_created": "2015-08-12 11:57:23",
            "date_modified": "2015-08-12 11:57:23",
            "done": False
        }

## Single Item in a Bucketlist [/bucketlists/<id>/items/<item_id>]

### Update this Bucket List Item [PUT]

+ Request (application/json)

    + Headers

            Authorization: JWT Token

    + Body

            {
                "id": 1,
                "item_id": 1,
                "name": "I need to do Z",
                "date_modified": "2015-08-12 11:59:23",
                "done": True
            }

+ Response 200 (application/json)

        {
            "id": 1,
            "item_id": 1,
            "name": "I need to do Z",
            "date_created": "2015-08-12 11:57:23",
            "date_modified": "2015-08-12 11:59:23",
            "done": True
        }

### Delete this Bucket List Item [DELETE]

+ Request (application/json)

    + Headers

            Authorization: JWT Token

+ Response 204 (application/json)